# name: Deploy Lambda Functions

# on:
#   push:
#     branches: [main]
#     paths:
#       - 'lambdas/**'
#       - '.github/workflows/deploy.yml'

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Setup Python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.11'

#       - name: Zip and Upload Lambdas
#         run: |
#           for dir in lambdas/*; do
#             cd $dir
#             zip -r function.zip . > /dev/null
#             aws s3 cp function.zip s3://my-lambda-artifacts-bucket/$(basename $dir)/function.zip
#             cd -
#           done
