name: NSP Bolt Ride CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Run tests
      #   run: |
      #     pytest tests/ --cov=lambdas --cov=glue_jobs --cov=simulator --cov-report=xml

      - name: Upload coverage report
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install TripStartProcessor dependencies
        working-directory: lambdas/TripStartProcessor
        run: |
         pip install -r requirements.txt -t .

      - name: Install TripEndProcessor dependencies
        working-directory: lambdas/TripEndProcessor
        run: |
         pip install -r requirements.txt -t .


      - name: Build Lambda ZIPs
        run: |
          cd lambdas
          zip -r9 TripStartProcessor.zip TripStartProcessor
          zip -r9 TripEndProcessor.zip TripEndProcessor

      # - name: Deploy CloudFormation stack
      #   run: |
      #     aws cloudformation deploy \
      #       --template-file infrastructure/template.yaml \
      #       --stack-name nsp-bolt-trip-pipeline \
      #       --capabilities CAPABILITY_NAMED_IAM \
      #       --region us-east-1

      - name: Deploy Lambda functions
        run: |
          aws lambda update-function-code \
            --function-name TripStartProcessor \
            --zip-file fileb://lambdas/TripStartProcessor.zip \
            --region us-east-1
          aws lambda update-function-code \
            --function-name TripEndProcessor \
            --zip-file fileb://lambdas/TripEndProcessor.zip \
            --region us-east-1

      - name: Deploy Step Functions state machine
        run: |
          aws stepfunctions create-state-machine \
            --name KPIOrchestrator \
            --definition file://stepfunction/stepfn.json \
            --role-arn arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/StepFunctionsExecutionRole \
            --region us-east-1 \
            --no-cli-pager || aws stepfunctions update-state-machine \
              --state-machine-arn arn:aws:states:us-east-1:${{ secrets.AWS_ACCOUNT_ID }}:stateMachine:KPIOrchestrator \
              --definition file://stepfunction/stepfn.json \
              --role-arn arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/StepFunctionsExecutionRole
        

      - name: Configure CloudWatch Events Rule
        run: |
          aws events put-rule \
            --name DailyKPIOrchestration \
            --schedule-expression "cron(0 0 * * ? *)" \
            --region us-east-1 \
            --no-cli-pager || aws events put-rule \
              --name DailyKPIOrchestration \
              --schedule-expression "cron(0 0 * * ? *)" \
              --region us-east-1
          aws events put-targets \
            --rule DailyKPIOrchestration \
            --targets "Id=1,Arn=arn:aws:states:us-east-1:${{ secrets.AWS_ACCOUNT_ID }}:stateMachine:KPIOrchestrator" \
            --region us-east-1

      - name: Upload Glue script to S3
        run: |
          aws s3 cp glue_jobs/KPI-Aggregator.py s3://nsp-kpi-results-bucket/glue_scripts/KPI-Aggregator.py \
            --region us-east-1

      - name: Update Glue job
        run: |
          aws glue create-job \
            --name daily_kpi_aggregator \
            --role arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GlueExecutionRole \
            --command "Name=glueetl,ScriptLocation=s3://nsp-kpi-results-bucket/glue_scripts/KPI-Aggregator.py" \
            --default-arguments '{"--TempDir":"s3://nsp-kpi-results-bucket/temp/","--job-language":"python"}' \
            --region us-east-1 \
            --no-cli-pager || aws glue update-job \
              --job-name daily_kpi_aggregator \
              --job-update "Role=arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GlueExecutionRole,Command={Name=glueetl,ScriptLocation=s3://nsp-kpi-results-bucket/glue_scripts/KPI-Aggregator.py},DefaultArguments={\"--TempDir\":\"s3://nsp-kpi-results-bucket/temp/\",\"--job-language\":\"python\"}"
